<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CetCompat>false</CetCompat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MentalHealthAssessment.Domain\MentalHealthAssessment.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.10.0" />
  </ItemGroup>
</Project>
